name: firstfind
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 

  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  flutter_carousel_widget: ^2.3.0
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_dash: ^1.0.0
  barcode_scan2: ^4.4.0
  lottie: ^3.3.1
  share_plus: ^10.1.4
  url_launcher: ^6.1.14
  file_picker: ^8.3.5

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

  

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/svgs/
    - assets/lotties/
    - assets/images/bank/
    - assets/images/storeProfile/
    - assets/images/kyc/
    - assets/icons/home_icons/
    - assets/images/store_logo_&_cover/
    - assets/icons/faq_grid_icons/
    - assets/icons/registration_stepper_icons/
    - assets/icons/select_store_module_icons/
    - assets/icons/store_category_grid_icons/
